starlight:
  target: development
  outputs:
    development:
      type: snowflake
      account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}"
      user: "{{ env_var('SNOWFLAKE_USER') }}"
      role: dbt

      password: "{{ env_var('SNOWFLAKE_PASSWORD') }}"

      database: datawarehouse
      warehouse: dbt
      schema: "{{ env_var('SNOWFLAKE_USER') }}"
      threads: 16
      client_session_keep_alive: false
    production:
      type: snowflake
      account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}"
      user: "{{ env_var('SNOWFLAKE_USER') }}"
      role: dbt

      password: "{{ env_var('SNOWFLAKE_PASSWORD') }}"

      database: datawarehouse
      warehouse: dbt
      schema: datawarehouse
      threads: 16
      client_session_keep_alive: false